name: Build and Deploy Frontend to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build (exports client envs)
        working-directory: frontend
        env:
          # client-only values from GitHub repo secrets -- set these in repo Settings -> Secrets -> Actions
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          # optional: REACT_APP_API_URL or NEXT_PUBLIC_API_URL if your frontend needs it
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  # change to ./.next if Next export, or build output dir
